apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ include "chat-app.namespace" . }}
spec:
{{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicas }}
{{- end }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.targetPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.probes.readiness.path }}
              port: {{ .Values.backend.probes.readiness.port }}
            initialDelaySeconds: {{ .Values.backend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.backend.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.probes.liveness.path }}
              port: {{ .Values.backend.probes.liveness.port }}
            initialDelaySeconds: {{ .Values.backend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.backend.probes.liveness.failureThreshold }}
          env:
            - name: MONGODB_URI
              value: {{ .Values.backend.env.mongodbUri | quote }}
            - name: PORT
              value: {{ .Values.backend.env.port | quote }}
            - name: NODE_ENV
              value: {{ .Values.backend.env.nodeEnv | quote }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.secretRef.name }}
                  key: {{ .Values.backend.secretRef.keys.jwtSecret }}
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.secretRef.name }}
                  key: {{ .Values.backend.secretRef.keys.cloudinaryCloudName }}
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.secretRef.name }}
                  key: {{ .Values.backend.secretRef.keys.cloudinaryApiKey }}
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.secretRef.name }}
                  key: {{ .Values.backend.secretRef.keys.cloudinaryApiSecret }}
          resources:
{{- toYaml .Values.backend.resources | nindent 12 }}
