{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-app
  namespace: {{ include "chat-app.namespace" . }}
  annotations:
{{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.paths.api }}
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: {{ .Values.ingress.paths.socket }}
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: {{ .Values.ingress.paths.root }}
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}
