{{- if .Values.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecret.name }}
  namespace: {{ include "chat-app.namespace" . }}
spec:
  encryptedData:
    cloudinary-api-key: {{ .Values.sealedSecret.encryptedData.cloudinaryApiKey | quote }}
    cloudinary-api-secret: {{ .Values.sealedSecret.encryptedData.cloudinaryApiSecret | quote }}
    cloudinary-cloud-name: {{ .Values.sealedSecret.encryptedData.cloudinaryCloudName | quote }}
    jwt-secret: {{ .Values.sealedSecret.encryptedData.jwtSecret | quote }}
  template:
    metadata:
      name: {{ .Values.sealedSecret.name }}
      namespace: {{ include "chat-app.namespace" . }}
{{- end }}
