{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: {{ include "chat-app.namespace" . }}
  labels:
    app: backend
    release: {{ .Values.metrics.serviceMonitor.prometheusRelease }}
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - {{ include "chat-app.namespace" . }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
